"""Cross-implementation parity: replay every shared fixture through the Python engine.

The fixtures under packages/signals/fixtures/ were generated by the TypeScript reference.
Numbers must agree within 1e-9, everything else must be identical, including key sets and
whether a number is an integer count or a rounded float.
"""

from __future__ import annotations

import datetime as dt
import json
from pathlib import Path

import pytest

from signalyze_api.engine import analyze
from signalyze_api.models import Review

FIXTURE_DIR = (
    Path(__file__).resolve().parents[1] / ".." / ".." / "packages" / "signals" / "fixtures"
).resolve()

if not FIXTURE_DIR.exists():
    pytest.skip("monorepo fixtures not present (e.g. inside Docker)", allow_module_level=True)

FIXTURE_FILES = sorted(FIXTURE_DIR.glob("*.json"))

# Keys whose values are integer counts in the reference; every other number is a round6 float
# (or a rounded score/identifier handled explicitly below).
INT_KEYS = {
    "score",
    "reviewCount",
    "count",
    "peakCount",
    "lifespanDays",
    "windowDays",
    "known",
    "singles",
    "minKnown",
    "noTextCount",
    "shortTextChars",
    "highPairs",
    "pairs",
    "eligible",
    "minEligible",
    "phraseBased",
    "withText",
    "minWithText",
    "scored",
    "mismatches",
    "minScored",
    "monthsInSpan",
    "activeMonths",
    "minMonths",
    "established",
    "exposed",
    "establishedLevel",
    "responded",
    "distinctResponses",
    "minResponded",
    "1",
    "2",
    "3",
    "4",
    "5",
}

TOLERANCE = 1e-9


def _is_number(value: object) -> bool:
    return isinstance(value, (int, float)) and not isinstance(value, bool)


def differences(actual: object, expected: object, path: str, key: str) -> list[str]:
    if isinstance(expected, bool) or isinstance(actual, bool):
        if type(actual) is not type(expected) or actual != expected:
            return [f"{path}: {actual!r} != {expected!r}"]
        return []
    if _is_number(expected) and _is_number(actual):
        assert isinstance(actual, (int, float))
        assert isinstance(expected, (int, float))
        problems: list[str] = []
        if abs(actual - expected) > TOLERANCE:
            problems.append(f"{path}: {actual!r} != {expected!r} (diff {actual - expected:.3e})")
        if key in INT_KEYS and type(actual) is not int:
            problems.append(f"{path}: expected an integer, got {type(actual).__name__} {actual!r}")
        if key not in INT_KEYS and type(actual) is not float:
            problems.append(f"{path}: expected a float, got {type(actual).__name__} {actual!r}")
        return problems
    if isinstance(expected, dict) and isinstance(actual, dict):
        problems = []
        missing = sorted(set(expected) - set(actual))
        extra = sorted(set(actual) - set(expected))
        if missing:
            problems.append(f"{path}: missing keys {missing}")
        if extra:
            problems.append(f"{path}: unexpected keys {extra}")
        for k in expected:
            if k in actual:
                problems.extend(differences(actual[k], expected[k], f"{path}.{k}", k))
        return problems
    if isinstance(expected, list) and isinstance(actual, list):
        if len(expected) != len(actual):
            return [f"{path}: length {len(actual)} != {len(expected)}"]
        problems = []
        for i, (a, e) in enumerate(zip(actual, expected, strict=True)):
            problems.extend(differences(a, e, f"{path}[{i}]", key))
        return problems
    if type(actual) is not type(expected) or actual != expected:
        return [f"{path}: {actual!r} != {expected!r}"]
    return []


def test_fixtures_exist() -> None:
    assert len(FIXTURE_FILES) >= 7


@pytest.mark.parametrize("fixture_path", FIXTURE_FILES, ids=[p.stem for p in FIXTURE_FILES])
def test_fixture_replays_exactly(fixture_path: Path) -> None:
    fixture = json.loads(fixture_path.read_text(encoding="utf-8"))
    reviews = [Review.model_validate(r) for r in fixture["reviews"]]
    now = dt.datetime.fromisoformat(fixture["now"])
    result = analyze(reviews, fixture["placeId"], "server", now)
    actual = result.model_dump(mode="json", by_alias=True)
    problems = differences(actual, fixture["expected"], fixture_path.stem, "")
    assert problems == [], "\n".join(problems)
